package pt.diamondcars.catalogbackend.domain.car;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderBy;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import pt.diamondcars.catalogbackend.domain.support.AbstractEntity;

/**
 * A car in the public catalog, mapped over the {@code cars} table of {@code V1__init.sql}.
 *
 * <p>This is a read-only projection of the car as shown on the public site ({@code dc}), not a
 * copy of the full back-office model: internal fields such as purchase price, consignment flag,
 * partner or client never appear here (TASK-013, {@code ## Notas}). {@link #id} is deliberately
 * <b>not</b> generated by this service — it is assigned by {@code dcbo-backend} when a car is
 * created and propagated verbatim on every sync call ({@code POST /internal/cars}, TASK-016),
 * which is what lets {@code dcbo-backend} perform an idempotent upsert and lets the public site
 * keep stable car URLs across the two backends.
 *
 * <p>Scalar business attributes ({@code marca}, {@code preco}, {@code vendido}, ...) stay in
 * Portuguese, per {@code backlog/CONVENTIONS.md} ADR-001 (Camada 2): this is how the {@code dc}
 * frontend already writes them, and this entity was born already conformant to ADR-001 (no
 * corrective migration needed, unlike {@code dcbo-backend}).
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(of = {"marca", "modelo", "ano", "preco", "vendido", "reservado", "destaque"})
@Entity
@Table(name = "cars")
public class Car extends AbstractEntity {

	/**
	 * Primary key assigned by {@code dcbo-backend} at sync time — no {@code @GeneratedValue}, no
	 * {@link org.hibernate.annotations.UuidGenerator}, by design (TASK-013 requirement 2).
	 */
	@Id
	@Column(name = "id", nullable = false, updatable = false)
	private UUID id;

	@Column(name = "marca", nullable = false, length = 100)
	private String marca;

	@Column(name = "modelo", nullable = false, length = 100)
	private String modelo;

	@Column(name = "ano", nullable = false)
	private int ano;

	@Column(name = "preco", nullable = false, precision = 12, scale = 2)
	private BigDecimal preco;

	@Column(name = "km", nullable = false)
	private int km;

	@Column(name = "cor", nullable = false, length = 50)
	private String cor;

	@Column(name = "combustivel", nullable = false, length = 50)
	private String combustivel;

	@Column(name = "descricao", columnDefinition = "TEXT")
	private String descricao;

	@Column(name = "observacoes", columnDefinition = "TEXT")
	private String observacoes;

	@Builder.Default
	@Column(name = "garantia_meses", nullable = false)
	private int garantiaMeses = 0;

	@Builder.Default
	@Column(name = "vendido", nullable = false)
	private boolean vendido = false;

	@Builder.Default
	@Column(name = "reservado", nullable = false)
	private boolean reservado = false;

	@Builder.Default
	@Column(name = "destaque", nullable = false)
	private boolean destaque = false;

	/**
	 * When this car's data was last written by a successful sync from {@code dcbo-backend} — kept
	 * here only for diagnosis of the sync flow (TASK-013 requirement 2), updated by the sync code
	 * of TASK-016, never by anything in this class.
	 */
	@Column(name = "synced_at")
	private OffsetDateTime syncedAt;

	@CreationTimestamp
	@Column(name = "created_at", nullable = false, updatable = false)
	private OffsetDateTime createdAt;

	@UpdateTimestamp
	@Column(name = "updated_at", nullable = false)
	private OffsetDateTime updatedAt;

	/**
	 * {@code @BatchSize} fetches the {@link CarImage} collections of up to 50 cars in a single
	 * {@code IN (...)} query, instead of one query per car — the same rationale already applied to
	 * {@code dcbo-backend}'s {@code Car.images}.
	 */
	@Builder.Default
	@OneToMany(mappedBy = "car", cascade = CascadeType.ALL, orphanRemoval = true)
	@OrderBy("position ASC")
	@BatchSize(size = 50)
	private List<CarImage> images = new ArrayList<>();

	/**
	 * Adds a photo to this car, keeping both sides of the bidirectional {@code car_images}
	 * association in sync (required because {@link CarImage} is the owning side of the {@code
	 * car_id} foreign key, so Hibernate never infers it from the inverse {@link #images} side).
	 *
	 * @param image the image to attach; its {@code car} back-reference is set to {@code this}
	 */
	public void addImage(CarImage image) {
		images.add(image);
		image.setCar(this);
	}

	/**
	 * Removes a photo from this car, keeping both sides of the bidirectional association in sync
	 * and letting {@code orphanRemoval = true} delete the row on flush.
	 *
	 * @param image the image to detach
	 */
	public void removeImage(CarImage image) {
		images.remove(image);
		image.setCar(null);
	}
}
