package pt.diamondcars.catalogbackend.domain.support;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import java.util.UUID;
import lombok.Getter;
import org.hibernate.annotations.UuidGenerator;

/**
 * Extends {@link AbstractEntity} with a locally-generated primary key, for every catalog entity
 * except {@link pt.diamondcars.catalogbackend.domain.car.Car} (whose id is assigned externally by
 * the sync from {@code dcbo-backend}, TASK-013 requirement 2, so it declares its own {@code @Id}
 * instead of extending this class).
 *
 * <p>{@code id} is generated by Hibernate ({@link UuidGenerator}) as a random {@link UUID},
 * matching the {@code UUID PRIMARY KEY DEFAULT gen_random_uuid()} convention used by {@code
 * car_images} and {@code leads} in {@code V1__init.sql}.
 */
@Getter
@MappedSuperclass
public abstract class AbstractGeneratedIdEntity extends AbstractEntity {

	@Id
	@UuidGenerator
	@Column(name = "id", nullable = false, updatable = false)
	private UUID id;
}
